url:         http://futurepixels.co.uk/
lsi:         false
paginate:    6
permalink:   /:categories/:title
pygments:    true
markdown:    kramdown
environment: prod

author:
  - name: Nigel Greenway
  - twitter: smilinmonki666

description: This is the description...
keywords: here, are, the, keywords

exclude: ['inuit.css', 'logs', 'doc', 'logo.html', 'projects.html']
