url:         http://futurepixels.co.uk/
lsi:         false
paginate:    6
permalink:   /:categories/:title
highligher:  pygments
markdown:    kramdown
environment: prod
safe: false
gems:
  - jekyll-paginate

author:
  name: Nigel Greenway
  twitter: NigelGreenway

description: This is the description...
keywords: here, are, the, keywords

current_os:
  - title: Elementary OS
  - url: http://elementary.io/

skills:
  - title: Frontend
    items:
      - HTML
      - HTML5
      - CSS2
      - CSS3
      - Javascript
      - jQuery
      - SASS
      - BEM
      - Gulp
      - Grunts

  - title: Languages
    items:
      - PHP
      - Ruby
      - Python
      - Go
      - NodeJS

  - title: DevOps
    items:
      - MySQL
      - Apache
      - Git
      - Bash
      - ZSH
      - Nginx
      - Hiawatha
      - Ansible

  - title: Frameworks
    items:
      - Symfony2
      - Silex
      - Slim

  - title: Miscellaneous 
    items:
      - PSR
      - TDD
      - BDD
      - DDD

  - title: Tools
    items:
    - Makefile
    - Vagrant
    - PHP Storm IDE
    - Sublime Text
    - Vim
    - OS X
    - Linux (Ubuntu | CentOS | Fedora)
    - tmux

readingList:
  - name: CSS Wizardry
    url: http://csswizardry.com
  - name: Integralist
    url: http://integralist.co.uk
  - name: CSS Tricks
    url: http://css-tricks.com
  - name: Inuit CSS
    url: http://inuitcss.com
  - name: A List Apart
    url: http://alistapart.com
  - name: Little Big Details
    url: http://littlebigdetails.com
  - name: David Walsh
    url: http://davidwalsh.name
  - name: Anthony Ferrara
    url: http://blog.ircmaxell.com/
  - name: Phil Sturgeon
    url: https://philsturgeon.uk
  - name: Mathias Verraes
    url: http://verraes.net/

exclude: ['inuit.css', 'logs', 'doc']
